$token = "YOUR_SUPABASE_TOKEN"
$project = "yvbemthdkmsplstihpxr"
$api = "https://api.supabase.com/v1/projects/$project/database/query"

$adminId = "b1dd62e9-1fd3-4179-90d8-0c4055665842"

# Category IDs
$cats = @{
  business       = "7d86d338-4f23-43fe-b8c9-884a71d3d0d7"
  contentwriting = "16efe92c-897a-403f-9f4b-0dfab86f0f71"
  creativearts   = "fdb7d75b-8bdd-4239-bd01-623e2d21d89c"
  education      = "2467ffeb-df0c-42f0-89d3-fc2e5fe758fc"
  healthwellness = "17a0ef8f-e17f-4355-8cf0-4a9692f11a21"
  marketing      = "9e01e8f5-854e-40ab-9290-7aa4644823f2"
  productivity   = "ac047257-4486-485a-b9af-e516865fcd43"
  programming    = "fd15bb95-c0d7-44af-85ea-649950d6c7a7"
}

function img($id) { return "https://picsum.photos/seed/prompt$id/800/600" }

$prompts = @()

# ─── BUSINESS (12) ───
$biz = @(
  @{title="Business Plan Generator";slug="business-plan-generator";desc="Generate a comprehensive business plan with market analysis";content="Create a detailed business plan for {{BusinessName}} in the {{Industry}} industry. Target market: {{TargetMarket}}. Include: executive summary, market analysis, competitive landscape, marketing strategy, operational plan, financial projections for {{Timeframe}} months. Business stage: {{Stage}}.";diff="Advanced";use="Entrepreneurs planning a new venture";tags=@("business-plan","startup","strategy");vars=@("BusinessName","Industry","TargetMarket","Timeframe","Stage")},
  @{title="Pitch Deck Creator";slug="pitch-deck-creator";desc="Craft a compelling investor pitch deck";content="Create a {{SlideCount}}-slide pitch deck for {{CompanyName}}, a {{Industry}} startup seeking `${{FundingAmount}} in {{RoundType}} funding. Key metrics: {{Metric1}}, {{Metric2}}, {{Metric3}}. Competitive advantage: {{Advantage}}.";diff="Intermediate";use="Startups preparing for investor meetings";tags=@("pitch-deck","fundraising","investors");vars=@("CompanyName","Industry","FundingAmount","RoundType","Metric1","Metric2","Metric3","Advantage","SlideCount")},
  @{title="SWOT Analysis Tool";slug="swot-analysis-tool";desc="Deep-dive SWOT analysis for strategic planning";content="Conduct a SWOT analysis for {{OrganizationName}}. Strengths: {{Strength1}}, {{Strength2}}, {{Strength3}}. Weaknesses: {{Weakness1}}, {{Weakness2}}. Opportunities: {{Opportunity1}}, {{Opportunity2}}, {{Opportunity3}}. Threats: {{Threat1}}, {{Threat2}}. Provide strategic recommendations based on this analysis.";diff="Beginner";use="Business strategists and managers";tags=@("swot","strategy","analysis");vars=@("OrganizationName","Strength1","Strength2","Strength3","Weakness1","Weakness2","Opportunity1","Opportunity2","Opportunity3","Threat1","Threat2")},
  @{title="Market Research Report";slug="market-research-report";desc="Generate a detailed market research report";content="Compile a market research report for {{ProductName}} in the {{Industry}} sector. Market size: {{MarketSize}}. Growth rate: {{GrowthRate}}. Target demographics: {{Demographics}}. Key competitors: {{Competitor1}}, {{Competitor2}}, {{Competitor3}}. Customer pain points: {{PainPoint1}}, {{PainPoint2}}. Include primary research methodology and data sources.";diff="Advanced";use="Product managers and market analysts";tags=@("market-research","analysis","report");vars=@("ProductName","Industry","MarketSize","GrowthRate","Demographics","Competitor1","Competitor2","Competitor3","PainPoint1","PainPoint2")},
  @{title="Executive Summary Writer";slug="executive-summary-writer";desc="Write a powerful executive summary";content="Write an executive summary for {{DocumentType}} about {{Topic}}. Key findings: {{Finding1}}, {{Finding2}}, {{Finding3}}. Recommendations: {{Recommendation1}}, {{Recommendation2}}. Target audience: {{Audience}}. Tone: {{Tone}}. Max {{MaxWords}} words.";diff="Beginner";use="Executives and consultants";tags=@("executive-summary","business-writing");vars=@("DocumentType","Topic","Finding1","Finding2","Finding3","Recommendation1","Recommendation2","Audience","Tone","MaxWords")},
  @{title="Competitive Analysis Matrix";slug="competitive-analysis-matrix";desc="Build a feature-by-feature competitive comparison";content="Create a competitive analysis comparing {{CompanyName}} against {{Competitor1}}, {{Competitor2}}, and {{Competitor3}}. Compare across: {{Criteria1}}, {{Criteria2}}, {{Criteria3}}, {{Criteria4}}, {{Criteria5}}. Market position: {{Position}}. Provide a strategic gap analysis and action plan.";diff="Intermediate";use="Product teams and business strategists";tags=@("competitive-analysis","strategy");vars=@("CompanyName","Competitor1","Competitor2","Competitor3","Criteria1","Criteria2","Criteria3","Criteria4","Criteria5","Position")},
  @{title="Business Model Canvas";slug="business-model-canvas";desc="Complete a Business Model Canvas";content="Fill out a Business Model Canvas for {{VentureName}}. Value Proposition: {{ValueProp}}. Customer Segments: {{Segments}}. Channels: {{Channels}}. Customer Relationships: {{Relationships}}. Revenue Streams: {{Revenue}}. Key Resources: {{Resources}}. Key Activities: {{Activities}}. Key Partners: {{Partners}}. Cost Structure: {{Costs}}.";diff="Beginner";use="Entrepreneurs and innovation teams";tags=@("business-model","canvas","lean-startup");vars=@("VentureName","ValueProp","Segments","Channels","Relationships","Revenue","Resources","Activities","Partners","Costs")},
  @{title="Risk Assessment Framework";slug="risk-assessment-framework";desc="Identify and mitigate business risks";content="Assess risks for {{ProjectName}}. Categorize by: financial, operational, strategic, compliance. For each risk: likelihood ({{Likelihood}}), impact ({{Impact}}), mitigation strategy. Time horizon: {{TimeHorizon}}. Industry: {{Industry}}. Provide a risk heat map and priority action items.";diff="Advanced";use="Project managers and risk officers";tags=@("risk-assessment","risk-management");vars=@("ProjectName","Likelihood","Impact","TimeHorizon","Industry")},
  @{title="Partnership Proposal Template";slug="partnership-proposal";desc="Draft a strategic partnership proposal";content="Draft a partnership proposal from {{SenderCompany}} to {{TargetCompany}}. Partnership type: {{PartnershipType}}. Value proposition: {{ValueProp}}. Proposed terms: {{Term1}}, {{Term2}}, {{Term3}}. Expected outcomes: {{Outcome1}}, {{Outcome2}}. Timeline: {{Timeline}}. Decision deadline: {{Deadline}}.";diff="Intermediate";use="Business development teams";tags=@("partnership","proposal","b2b");vars=@("SenderCompany","TargetCompany","PartnershipType","ValueProp","Term1","Term2","Term3","Outcome1","Outcome2","Timeline","Deadline")},
  @{title="Quarterly Business Review";slug="quarterly-business-review";desc="Generate a QBR presentation script";content="Create a QBR script for {{Department}} department. Quarter: {{Quarter}}. Key achievements: {{Achievement1}}, {{Achievement2}}, {{Achievement3}}. KPIs: {{KPI1}} ({{KPI1Value}}), {{KPI2}} ({{KPI2Value}}). Challenges: {{Challenge1}}, {{Challenge2}}. Next quarter goals: {{Goal1}}, {{Goal2}}, {{Goal3}}. Resource needs: {{Resources}}.";diff="Intermediate";use="Department heads and managers";tags=@("qbr","review","presentation");vars=@("Department","Quarter","Achievement1","Achievement2","Achievement3","KPI1","KPI1Value","KPI2","KPI2Value","Challenge1","Challenge2","Goal1","Goal2","Goal3","Resources")},
  @{title="Exit Strategy Planner";slug="exit-strategy-planner";desc="Plan acquisition or IPO exit strategy";content="Develop an exit strategy for {{CompanyName}}, a {{Industry}} company with `${{Revenue}} revenue. Exit options: {{Option1}}, {{Option2}}. Timeline: {{Timeline}} years. Valuation target: `${{Valuation}}. Key preparation steps: {{Step1}}, {{Step2}}, {{Step3}}, {{Step4}}. Advisors needed: {{Advisors}}.";diff="Advanced";use="Founders and board members";tags=@("exit-strategy","acquisition","ipo");vars=@("CompanyName","Industry","Revenue","Option1","Option2","Timeline","Valuation","Step1","Step2","Step3","Step4","Advisors")},
  @{title="Meeting Agenda Generator";slug="meeting-agenda-generator";desc="Structure productive meeting agendas";content="Create an agenda for a {{MeetingType}} meeting. Duration: {{Duration}} minutes. Attendees: {{Attendees}}. Objective: {{Objective}}. Topics: 1. {{Topic1}} ({{Min1}}min), 2. {{Topic2}} ({{Min2}}min), 3. {{Topic3}} ({{Min3}}min). Pre-read materials: {{PreRead}}. Decision needed: {{Decision}}.";diff="Beginner";use="Team leads and facilitators";tags=@("meeting","agenda","productivity");vars=@("MeetingType","Duration","Attendees","Objective","Topic1","Min1","Topic2","Min2","Topic3","Min3","PreRead","Decision")}
)
foreach ($p in $biz) { $p.category_id = $cats.business; $prompts += $p }

# ─── CONTENT WRITING (12) ───
$cw = @(
  @{title="SEO Blog Post Writer";slug="seo-blog-post-writer";desc="Write SEO-optimized blog posts";content="Write a {{WordCount}}-word SEO blog post titled '{{Title}}'. Target keyword: {{Keyword}}. Secondary keywords: {{KW2}}, {{KW3}}. Target audience: {{Audience}}. Tone: {{Tone}}. Include: H2 headings, intro, body sections, conclusion, FAQ section with {{FAQCount}} questions. Meta description: {{MetaDesc}}. Call to action: {{CTA}}.";diff="Intermediate";use="Content marketers and bloggers";tags=@("seo","blog","content-marketing");vars=@("Title","WordCount","Keyword","KW2","KW3","Audience","Tone","FAQCount","MetaDesc","CTA")},
  @{title="Email Copy Generator";slug="email-copy-generator";desc="Craft high-converting email campaigns";content="Write a {{EmailType}} email for {{CompanyName}}. Subject line: {{SubjectLine}}. Preheader: {{Preheader}}. Goal: {{Goal}}. Audience segment: {{Segment}}. Key message: {{Message}}. CTA: {{CTA}}. Offer: {{Offer}}. Urgency: {{Urgency}}. Include personalization tokens for {{FirstName}}, {{Company}}.";diff="Beginner";use="Email marketers and growth teams";tags=@("email","copywriting","marketing");vars=@("EmailType","CompanyName","SubjectLine","Preheader","Goal","Segment","Message","CTA","Offer","Urgency","FirstName","Company")},
  @{title="Newsletter Creator";slug="newsletter-creator";desc="Engaging newsletter content generation";content="Create a {{Frequency}} newsletter for {{Publication}}. Theme: {{Theme}}. Featured article: {{ArticleTitle}}. Secondary stories: {{Story1}}, {{Story2}}. Curated links: {{Link1}}, {{Link2}}. Personal note from {{AuthorName}} about {{PersonalTopic}}. Opening line: {{Opening}}. Closing: {{Closing}}. Include a poll: {{PollQuestion}}.";diff="Intermediate";use="Newsletter publishers and community builders";tags=@("newsletter","email","content");vars=@("Frequency","Publication","Theme","ArticleTitle","Story1","Story2","Link1","Link2","AuthorName","PersonalTopic","Opening","Closing","PollQuestion")},
  @{title="Product Description Writer";slug="product-description-writer";desc="Persuasive product descriptions that sell";content="Write a product description for {{ProductName}}. Key features: {{Feature1}}, {{Feature2}}, {{Feature3}}, {{Feature4}}. Benefits: {{Benefit1}}, {{Benefit2}}, {{Benefit3}}. Target customer: {{TargetCustomer}}. Price point: `${{Price}}. Unique selling point: {{USP}}. Tone: {{Tone}}. Include technical specs and a customer testimonial.";diff="Beginner";use="E-commerce managers and product marketers";tags=@("product-description","ecommerce","copy");vars=@("ProductName","Feature1","Feature2","Feature3","Feature4","Benefit1","Benefit2","Benefit3","TargetCustomer","Price","USP","Tone")},
  @{title="Press Release Generator";slug="press-release-generator";desc="Newsworthy press releases for media coverage";content="Write a press release for {{CompanyName}} announcing {{Announcement}}. Quote from {{Spokesperson}}, {{Title}}: '{{Quote}}'. Key details: {{Detail1}}, {{Detail2}}, {{Detail3}}. About {{CompanyName}}: {{CompanyDesc}}. Media contact: {{ContactName}}, {{ContactEmail}}. Distribution: {{Distribution}}. Embargo: {{Embargo}}.";diff="Intermediate";use="PR teams and communications managers";tags=@("press-release","pr","media");vars=@("CompanyName","Announcement","Spokesperson","Title","Quote","Detail1","Detail2","Detail3","CompanyDesc","ContactName","ContactEmail","Distribution","Embargo")},
  @{title="Case Study Template";slug="case-study-template";desc="Compelling customer success stories";content="Create a case study featuring {{CustomerName}} ({{CustomerIndustry}}). Challenge: {{Challenge}}. Solution implemented: {{Solution}}. Results: {{Result1}}, {{Result2}}, {{Result3}}. ROI: {{ROI}}. Quote from {{QuoteSource}}: '{{Quote}}'. Format: {{Format}} (PDF/video/written). Length: {{Length}} words.";diff="Advanced";use="Sales and marketing teams";tags=@("case-study","testimonial","sales");vars=@("CustomerName","CustomerIndustry","Challenge","Solution","Result1","Result2","Result3","ROI","QuoteSource","Quote","Format","Length")},
  @{title="Social Media Caption Writer";slug="social-media-caption-writer";desc="Scroll-stopping social media captions";content="Write {{Count}} social media captions for {{Platform}}. Brand voice: {{Voice}}. Post topic: {{Topic}}. Include {{HashtagCount}} hashtags. CTA: {{CTA}}. Emoji style: {{EmojiStyle}}. Mention accounts: {{Mentions}}. Best posting time: {{PostTime}}. Content format: {{Format}} (image/video/carousel).";diff="Beginner";use="Social media managers and content creators";tags=@("social-media","captions","content");vars=@("Count","Platform","Voice","Topic","HashtagCount","CTA","EmojiStyle","Mentions","PostTime","Format")},
  @{title="White Paper Outline";slug="white-paper-outline";desc="Authoritative white paper structure";content="Outline a white paper on {{Topic}} for {{TargetAudience}}. Working title: {{Title}}. Problem statement: {{Problem}}. Research methodology: {{Methodology}}. Key findings: {{Finding1}}, {{Finding2}}, {{Finding3}}, {{Finding4}}. Data sources: {{DataSource1}}, {{DataSource2}}. Expert interviews: {{Expert1}}, {{Expert2}}. Recommendations: {{Recommendation}}. Pages: {{PageCount}}. Format: {{Format}}.";diff="Advanced";use="Thought leaders and content strategists";tags=@("white-paper","research","thought-leadership");vars=@("Topic","TargetAudience","Title","Problem","Methodology","Finding1","Finding2","Finding3","Finding4","DataSource1","DataSource2","Expert1","Expert2","Recommendation","PageCount","Format")},
  @{title="Copywriting Formula Applier";slug="copywriting-formula-applier";desc="Apply proven copywriting frameworks";content="Apply the {{Formula}} copywriting framework for {{ProductName}}. Formula: {{Formula}}. Target: {{Target}}. Problem: {{Problem}}. Agitate: {{Agitation}}. Solve: {{Solution}}. Proof: {{Proof}}. CTA: {{CTA}}. Tone: {{Tone}}. Medium: {{Medium}}. Length: {{Length}}.";diff="Intermediate";use="Copywriters and marketers";tags=@("copywriting","formula","persuasion");vars=@("Formula","ProductName","Target","Problem","Agitation","Solution","Proof","CTA","Tone","Medium","Length")},
  @{title="Video Script Writer";slug="video-script-writer";desc="Engaging video scripts for any platform";content="Write a {{VideoLength}}-minute video script for {{Platform}}. Video type: {{Type}}. Hook: {{Hook}}. Main points: {{Point1}}, {{Point2}}, {{Point3}}. Visual cues: {{Visual1}}, {{Visual2}}. Audio/music: {{AudioStyle}}. Call to action: {{CTA}}. Tone: {{Tone}}. Target audience: {{Audience}}. Include timestamps for each segment.";diff="Intermediate";use="Video creators and content marketers";tags=@("video","script","content-creation");vars=@("VideoLength","Platform","Type","Hook","Point1","Point2","Point3","Visual1","Visual2","AudioStyle","CTA","Tone","Audience")},
  @{title="Landing Page Copywriter";slug="landing-page-copywriter";desc="High-conversion landing page copy";content="Write landing page copy for {{Offer}}. Headline: {{Headline}}. Subheadline: {{Subheadline}}. Key benefits: {{Benefit1}}, {{Benefit2}}, {{Benefit3}}. Features: {{Feature1}}, {{Feature2}}. Social proof: {{SocialProof}} ({{ProofCount}} reviews). Risk reversal: {{RiskReversal}}. CTA button text: {{CTAText}}. Page sections: {{Sections}}. A/B test variant: {{Variant}}.";diff="Advanced";use="Growth marketers and product teams";tags=@("landing-page","conversion","copy");vars=@("Offer","Headline","Subheadline","Benefit1","Benefit2","Benefit3","Feature1","Feature2","SocialProof","ProofCount","RiskReversal","CTAText","Sections","Variant")},
  @{title="FAQ Content Generator";slug="faq-content-generator";desc="Comprehensive FAQ sections for websites";content="Generate {{Count}} FAQ items for {{Topic}}. Target audience: {{Audience}}. Question style: {{Style}}. Key concerns: {{Concern1}}, {{Concern2}}, {{Concern3}}. Include schema markup for SEO. Tone: {{Tone}}. Max answer length: {{MaxLength}} words. Group by category: {{Categories}}. Sources: {{Sources}}.";diff="Beginner";use="Content managers and support teams";tags=@("faq","content","support");vars=@("Count","Topic","Audience","Style","Concern1","Concern2","Concern3","Tone","MaxLength","Categories","Sources")}
)
foreach ($p in $cw) { $p.category_id = $cats.contentwriting; $prompts += $p }

# ─── CREATIVE ARTS (12) ───
$ca = @(
  @{title="Short Story Generator";slug="short-story-generator";desc="Create compelling short stories";content="Write a {{Genre}} short story titled '{{Title}}'. Main character: {{Protagonist}}, a {{CharacterAge}}-year-old {{CharacterTrait}}. Setting: {{Setting}}. Conflict: {{Conflict}}. Theme: {{Theme}}. Tone: {{Tone}}. Word count: {{WordCount}}. Include a twist ending. Point of view: {{POV}}. Opening line: '{{FirstLine}}'.";diff="Intermediate";use="Writers and creative storytellers";tags=@("story","fiction","creative-writing");vars=@("Genre","Title","Protagonist","CharacterAge","CharacterTrait","Setting","Conflict","Theme","Tone","WordCount","POV","FirstLine")},
  @{title="Poetry Composer";slug="poetry-composer";desc="Express through structured poetry";content="Compose a {{PoemType}} poem titled '{{Title}}'. Theme: {{Theme}}. Mood: {{Mood}}. Rhyme scheme: {{RhymeScheme}}. Stanzas: {{StanzaCount}}. Lines per stanza: {{LinesPerStanza}}. Literary devices: {{Device1}}, {{Device2}}. Include imagery of {{Imagery}}. Inspiration: {{Inspiration}}.";diff="Beginner";use="Poets and creative writers";tags=@("poetry","creative-writing","literary");vars=@("PoemType","Title","Theme","Mood","RhymeScheme","StanzaCount","LinesPerStanza","Device1","Device2","Imagery","Inspiration")},
  @{title="Character Creator";slug="character-creator";desc="Rich character profiles for stories";content="Create a character profile for {{Role}}. Name: {{CharacterName}}. Age: {{Age}}. Occupation: {{Occupation}}. Personality: {{PersonalityType}}. Backstory: {{Backstory}}. Motivation: {{Motivation}}. Flaw: {{Flaw}}. Arc: {{Arc}} (change over story). Relationships: {{Relationship1}}, {{Relationship2}}. Physical description: {{Appearance}}. Voice: {{Voice}}. Secret: {{Secret}}.";diff="Intermediate";use="Writers and game designers";tags=@("character","writing","rpg");vars=@("Role","CharacterName","Age","Occupation","PersonalityType","Backstory","Motivation","Flaw","Arc","Relationship1","Relationship2","Appearance","Voice","Secret")},
  @{title="Worldbuilding Engine";slug="worldbuilding-engine";desc="Build immersive fictional worlds";content="Design a world for {{Genre}} fiction. World name: {{WorldName}}. Geography: {{Geography}}. Climate: {{Climate}}. Civilizations: {{Civ1}}, {{Civ2}}. Magic system: {{MagicSystem}} (rules: {{Rules}}). Technology level: {{TechLevel}}. History: {{History}}. Conflicts: {{Conflict1}}, {{Conflict2}}. Unique flora/fauna: {{Flora}}, {{Fauna}}. Gods/religion: {{Religion}}.";diff="Advanced";use="Fantasy and sci-fi writers";tags=@("worldbuilding","fantasy","sci-fi");vars=@("Genre","WorldName","Geography","Climate","Civ1","Civ2","MagicSystem","Rules","TechLevel","History","Conflict1","Conflict2","Flora","Fauna","Religion")},
  @{title="Dialogue Writer";slug="dialogue-writer";desc="Natural conversation scenes";content="Write a dialogue scene between {{Character1}} and {{Character2}}. Setting: {{Setting}}. Mood: {{Mood}}. Conflict: {{Conflict}}. {{Character1}} wants {{Goal1}}. {{Character2}} wants {{Goal2}}. Subtext: {{Subtext}}. Scene length: {{Length}} lines. Include stage directions. Tone: {{Tone}}. End with: {{Resolution}}.";diff="Intermediate";use="Playwrights and fiction writers";tags=@("dialogue","script","writing");vars=@("Character1","Character2","Setting","Mood","Conflict","Goal1","Goal2","Subtext","Length","Tone","Resolution")},
  @{title="Song Lyric Generator";slug="song-lyric-generator";desc="Write lyrics for any genre";content="Write lyrics for a {{Genre}} song titled '{{Title}}'. Theme: {{Theme}}. Mood: {{Mood}}. Structure: {{Structure}}. Key lyric: {{KeyLine}}. Rhyme scheme: {{RhymeScheme}}. Length: {{Length}} lines. Vocal range: {{VocalRange}}. Instrumentation: {{Instruments}}. Inspiration: {{Inspiration}}. Write the chorus first, then verses.";diff="Advanced";use="Musicians and songwriters";tags=@("lyrics","music","songwriting");vars=@("Genre","Title","Theme","Mood","Structure","KeyLine","RhymeScheme","Length","VocalRange","Instruments","Inspiration")},
  @{title="Art Prompt Generator";slug="art-prompt-generator";desc="Inspirational prompts for visual artists";content="Create an art prompt: subject {{Subject}}, style {{Style}}, medium {{Medium}}, color palette {{Palette}}, mood {{Mood}}, composition {{Composition}}, lighting {{Lighting}}. Reference artists: {{Artist1}}, {{Artist2}}. Challenge: {{Challenge}}. Format: {{Format}}. Time estimate: {{TimeEstimate}}.";diff="Beginner";use="Visual artists and illustrators";tags=@("art","prompt","creative");vars=@("Subject","Style","Medium","Palette","Mood","Composition","Lighting","Artist1","Artist2","Challenge","Format","TimeEstimate")},
  @{title="Mythology Creator";slug="mythology-creator";desc="Invent myths and legends for your world";content="Create a myth for {{CultureName}}. Myth type: {{Type}}. Deities involved: {{Deity1}} ({{Domain1}}), {{Deity2}} ({{Domain2}}). Moral lesson: {{Lesson}}. Natural phenomenon explained: {{Phenomenon}}. Rituals: {{Ritual1}}, {{Ritual2}}. Sacred symbol: {{Symbol}}. Tell the story in {{WordCount}} words.";diff="Intermediate";use="Worldbuilders and fantasy writers";tags=@("mythology","fantasy","worldbuilding");vars=@("CultureName","Type","Deity1","Domain1","Deity2","Domain2","Lesson","Phenomenon","Ritual1","Ritual2","Symbol","WordCount")},
  @{title="Color Palette Designer";slug="color-palette-designer";desc="Harmonious color schemes for any project";content="Design a color palette for {{ProjectType}}. Base color: {{BaseColor}}. Mood: {{Mood}}. Style: {{Style}}. Number of colors: {{ColorCount}}. Include: primary, secondary, accent, background, text colors. Hex codes for each. Accessibility: ensure WCAG {{WCAGLevel}} contrast. Reference palette: {{Reference}}.";diff="Beginner";use="Designers and frontend developers";tags=@("color","design","palette");vars=@("ProjectType","BaseColor","Mood","Style","ColorCount","WCAGLevel","Reference")},
  @{title="Scene Description Engine";slug="scene-description-engine";desc="Vivid scene descriptions for writers";content="Describe a {{SettingType}} at {{TimeOfDay}}. Weather: {{Weather}}. Mood: {{Mood}}. Sensory details: sight: {{Sight}}, sound: {{Sound}}, smell: {{Smell}}, touch: {{Touch}}. Key objects: {{Object1}}, {{Object2}}. Characters present: {{Character1}}, {{Character2}}. Focal point: {{FocalPoint}}. POV: {{POV}}. Style: {{Style}}.";diff="Beginner";use="Novelists and descriptive writers";tags=@("description","scene","writing");vars=@("SettingType","TimeOfDay","Weather","Mood","Sight","Sound","Smell","Touch","Object1","Object2","Character1","Character2","FocalPoint","POV","Style")},
  @{title="Plot Twist Generator";slug="plot-twist-generator";desc="Unexpected twists that elevate stories";content="Generate a plot twist for a {{Genre}} story. Current direction: {{CurrentPlot}}. Protagonist: {{Protagonist}}. Antagonist: {{Antagonist}}. Twist type: {{TwistType}}. Revelation: {{Revelation}}. Foreshadowing: {{Clue1}}, {{Clue2}}. Impact on characters: {{Impact1}}, {{Impact2}}. Reader reaction: {{Reaction}}. Setup required: {{Setup}}.";diff="Advanced";use="Writers and screenwriters";tags=@("plot-twist","writing","narrative");vars=@("Genre","CurrentPlot","Protagonist","Antagonist","TwistType","Revelation","Clue1","Clue2","Impact1","Impact2","Reaction","Setup")},
  @{title="Creative Brief Generator";slug="creative-brief-generator";desc="Structured briefs for creative projects";content="Write a creative brief for {{ProjectName}}. Client: {{Client}}. Objective: {{Objective}}. Target audience: {{Audience}}. Key message: {{KeyMessage}}. Tone: {{Tone}}. Deliverables: {{Deliverable1}}, {{Deliverable2}}. Budget: `${{Budget}}. Timeline: {{Timeline}}. Success metrics: {{Metric1}}, {{Metric2}}. Mandatory elements: {{Mandatory}}. Style references: {{Reference}}.";diff="Intermediate";use="Creative directors and project managers";tags=@("creative-brief","project","brief");vars=@("ProjectName","Client","Objective","Audience","KeyMessage","Tone","Deliverable1","Deliverable2","Budget","Timeline","Metric1","Metric2","Mandatory","Reference")}
)
foreach ($p in $ca) { $p.category_id = $cats.creativearts; $prompts += $p }

# ─── EDUCATION (12) ───
$ed = @(
  @{title="Lesson Plan Creator";slug="lesson-plan-creator";desc="Comprehensive lesson plans for educators";content="Create a {{Duration}}-minute lesson plan for {{GradeLevel}} on {{Topic}}. Learning objectives: {{Objective1}}, {{Objective2}}, {{Objective3}}. Materials needed: {{Materials}}. Hook/engagement: {{Hook}}. Direct instruction: {{Instruction}}. Guided practice: {{Practice}}. Independent work: {{Work}}. Assessment: {{Assessment}}. Differentiation: {{Differentiation}}. Homework: {{Homework}}.";diff="Intermediate";use="Teachers and educators";tags=@("lesson-plan","education","teaching");vars=@("Duration","GradeLevel","Topic","Objective1","Objective2","Objective3","Materials","Hook","Instruction","Practice","Work","Assessment","Differentiation","Homework")},
  @{title="Quiz Generator";slug="quiz-generator";desc="Custom quizzes for any subject";content="Create a {{QuestionCount}}-question {{QuizType}} quiz on {{Subject}}. Difficulty: {{Difficulty}}. Question formats: {{Format1}}, {{Format2}}, {{Format3}}. Topics covered: {{Topic1}}, {{Topic2}}, {{Topic3}}. Time limit: {{TimeLimit}} minutes. Passing score: {{PassScore}}%. Answer key included. Instructions: {{Instructions}}.";diff="Beginner";use="Teachers and trainers";tags=@("quiz","assessment","education");vars=@("QuestionCount","QuizType","Subject","Difficulty","Format1","Format2","Format3","Topic1","Topic2","Topic3","TimeLimit","PassScore","Instructions")},
  @{title="Study Guide Generator";slug="study-guide-generator";desc="Structured study guides for exam prep";content="Create a study guide for {{ExamName}} in {{Subject}}. Key concepts: {{Concept1}}, {{Concept2}}, {{Concept3}}, {{Concept4}}. Definitions: define {{Term1}}, {{Term2}}, {{Term3}}. Formulas: {{Formula1}}, {{Formula2}}. Practice problems: {{ProblemCount}}. Mnemonics: {{Mnemonic1}}, {{Mnemonic2}}. Common mistakes: {{Mistake1}}, {{Mistake2}}. Review checklist: {{Checklist}}. Estimated study time: {{StudyTime}}.";diff="Intermediate";use="Students and tutors";tags=@("study-guide","exam","learning");vars=@("ExamName","Subject","Concept1","Concept2","Concept3","Concept4","Term1","Term2","Term3","Formula1","Formula2","ProblemCount","Mnemonic1","Mnemonic2","Mistake1","Mistake2","Checklist","StudyTime")},
  @{title="Course Curriculum Designer";slug="course-curriculum-designer";desc="Design complete course curricula";content="Design a {{CourseLength}}-week course on {{CourseTopic}} for {{Audience}}. Course title: {{CourseTitle}}. Prerequisites: {{Prereqs}}. Learning outcomes: {{Outcome1}}, {{Outcome2}}, {{Outcome3}}. Weekly breakdown: {{Week1Topic}}, {{Week2Topic}}, {{Week3Topic}}, {{Week4Topic}}. Assessment: {{Assessment}}. Resources: {{Resource1}}, {{Resource2}}. Capstone project: {{Capstone}}.";diff="Advanced";use="Curriculum designers and instructors";tags=@("curriculum","course","education");vars=@("CourseLength","CourseTopic","Audience","CourseTitle","Prereqs","Outcome1","Outcome2","Outcome3","Week1Topic","Week2Topic","Week3Topic","Week4Topic","Assessment","Resource1","Resource2","Capstone")},
  @{title="Flashcard Creator";slug="flashcard-creator";desc="Effective flashcards for memorization";content="Create {{Count}} flashcards for {{Subject}}. Topic: {{Topic}}. Format: {{Format}}. Include: term on front, definition on back for each. Add mnemonics: {{Mnemonic}}. Difficulty levels: {{Difficulty}}. Tags for organization: {{Tag1}}, {{Tag2}}. Spaced repetition schedule: {{Schedule}}.";diff="Beginner";use="Students and lifelong learners";tags=@("flashcards","memorization","study");vars=@("Count","Subject","Topic","Format","Mnemonic","Difficulty","Tag1","Tag2","Schedule")},
  @{title="Rubric Generator";slug="rubric-generator";desc="Clear grading rubrics for assignments";content="Create a grading rubric for {{AssignmentName}} in {{Subject}}. Criteria: {{Criterion1}} ({{Weight1}}%), {{Criterion2}} ({{Weight2}}%), {{Criterion3}} ({{Weight3}}%), {{Criterion4}} ({{Weight4}}%). Performance levels: {{Level1}} ({{L1Desc}}), {{Level2}} ({{L2Desc}}), {{Level3}} ({{L3Desc}}). Total points: {{TotalPoints}}. Feedback template: {{FeedbackTemplate}}.";diff="Intermediate";use="Teachers and professors";tags=@("rubric","grading","assessment");vars=@("AssignmentName","Subject","Criterion1","Weight1","Criterion2","Weight2","Criterion3","Weight3","Criterion4","Weight4","Level1","L1Desc","Level2","L2Desc","Level3","L3Desc","TotalPoints","FeedbackTemplate")},
  @{title="Educational Story Generator";slug="educational-story-generator";desc="Stories that teach concepts";content="Write an educational story for {{AgeGroup}} about {{Topic}}. Main character: {{Character}}. Setting: {{Setting}}. Learning objective: {{Objective}}. Concepts covered: {{Concept1}}, {{Concept2}}. Vocabulary words: {{Word1}}, {{Word2}}, {{Word3}}. Question to ask after: {{DiscussionQuestion}}. Length: {{WordCount}} words. Tone: {{Tone}}. Illustration prompts: {{Illustration1}}, {{Illustration2}}.";diff="Beginner";use="Elementary educators and parents";tags=@("educational-story","kids","learning");vars=@("AgeGroup","Topic","Character","Setting","Objective","Concept1","Concept2","Word1","Word2","Word3","DiscussionQuestion","WordCount","Tone","Illustration1","Illustration2")},
  @{title="Syllabus Template";slug="syllabus-template";desc="Comprehensive course syllabi";content="Create a syllabus for {{CourseName}} ({{CourseCode}}). Instructor: {{InstructorName}}. Credits: {{Credits}}. Prerequisites: {{Prereqs}}. Course description: {{Description}}. Required texts: {{Text1}}, {{Text2}}. Grading: {{GradeComponent1}} {{GradePct1}}%, {{GradeComponent2}} {{GradePct2}}%. Policies: {{Policy1}}, {{Policy2}}. Schedule: {{Schedule}}. Office hours: {{OfficeHours}}.";diff="Intermediate";use="Professors and course creators";tags=@("syllabus","course","academic");vars=@("CourseName","CourseCode","InstructorName","Credits","Prereqs","Description","Text1","Text2","GradeComponent1","GradePct1","GradeComponent2","GradePct2","Policy1","Policy2","Schedule","OfficeHours")},
  @{title="Debate Topic Generator";slug="debate-topic-generator";desc="Structured debate topics with pro/con";content="Create a debate on {{Topic}}. Format: {{Format}}. Position A: {{PositionA}}. Position B: {{PositionB}}. Key arguments for A: {{ArgA1}}, {{ArgA2}}. Key arguments for B: {{ArgB1}}, {{ArgB2}}. Evidence sources: {{Source1}}, {{Source2}}. Time limit: {{TimeLimit}} minutes. Judging criteria: {{Criteria}}. Audience: {{Audience}}.";diff="Advanced";use="Educators and debate coaches";tags=@("debate","argumentation","critical-thinking");vars=@("Topic","Format","PositionA","PositionB","ArgA1","ArgA2","ArgB1","ArgB2","Source1","Source2","TimeLimit","Criteria","Audience")},
  @{title="Worksheet Creator";slug="worksheet-creator";desc="Practice worksheets for any subject";content="Create a worksheet on {{Topic}} for {{GradeLevel}}. Question types: {{Type1}}, {{Type2}}, {{Type3}}. Number of questions: {{QuestionCount}}. Difficulty: {{Difficulty}}. Skills practiced: {{Skill1}}, {{Skill2}}. Answer key: {{AnswerKey}} (included/separate). Format: {{Format}}. Instructions: {{Instructions}}. Time estimate: {{TimeEstimate}} minutes.";diff="Beginner";use="Teachers and tutors";tags=@("worksheet","practice","education");vars=@("Topic","GradeLevel","Type1","Type2","Type3","QuestionCount","Difficulty","Skill1","Skill2","AnswerKey","Format","Instructions","TimeEstimate")},
  @{title="Research Paper Outline";slug="research-paper-outline";desc="Structured outlines for academic papers";content="Outline a research paper on {{Topic}}. Thesis statement: {{Thesis}}. Research question: {{ResearchQuestion}}. Methodology: {{Methodology}}. Literature review themes: {{Theme1}}, {{Theme2}}, {{Theme3}}. Sections: {{Section1}}, {{Section2}}, {{Section3}}, {{Section4}}. Data sources: {{DataSource1}}, {{DataSource2}}. Expected findings: {{Finding1}}, {{Finding2}}. References: {{ReferenceCount}} sources. Format: {{Format}}.";diff="Advanced";use="Students and researchers";tags=@("research","paper","academic");vars=@("Topic","Thesis","ResearchQuestion","Methodology","Theme1","Theme2","Theme3","Section1","Section2","Section3","Section4","DataSource1","DataSource2","Finding1","Finding2","ReferenceCount","Format")},
  @{title="Workshop Plan Generator";slug="workshop-plan-generator";desc="Interactive workshop designs";content="Design a {{Duration}}-hour workshop on {{Topic}}. Workshop title: {{Title}}. Learning objectives: {{Objective1}}, {{Objective2}}. Icebreaker: {{Icebreaker}}. Main activities: {{Activity1}} ({{Min1}}min), {{Activity2}} ({{Min2}}min), {{Activity3}} ({{Min3}}min). Materials: {{Materials}}. Group size: {{GroupSize}}. Facilitator notes: {{FacilitatorNotes}}. Takeaway: {{Takeaway}}.";diff="Intermediate";use="Trainers and facilitators";tags=@("workshop","training","facilitation");vars=@("Duration","Topic","Title","Objective1","Objective2","Icebreaker","Activity1","Min1","Activity2","Min2","Activity3","Min3","Materials","GroupSize","FacilitatorNotes","Takeaway")}
)
foreach ($p in $ed) { $p.category_id = $cats.education; $prompts += $p }

# ─── HEALTH & WELLNESS (12) ───
$hw = @(
  @{title="Workout Plan Designer";slug="workout-plan-designer";desc="Personalized fitness routines";content="Create a {{Duration}}-week workout plan for {{Goal}}. Experience level: {{Level}}. Days per week: {{Days}}. Session length: {{SessionLength}} minutes. Equipment: {{Equipment}}. Warmup: {{Warmup}}. Main exercises: {{Exercise1}}, {{Exercise2}}, {{Exercise3}}, {{Exercise4}}. Cooldown: {{Cooldown}}. Progression: {{Progression}}. Rest days: {{RestDays}}. Notes: {{Notes}}.";diff="Intermediate";use="Fitness enthusiasts and trainers";tags=@("workout","fitness","exercise");vars=@("Duration","Goal","Level","Days","SessionLength","Equipment","Warmup","Exercise1","Exercise2","Exercise3","Exercise4","Cooldown","Progression","RestDays","Notes")},
  @{title="Meal Planner";slug="meal-planner";desc="Balanced meal plans for dietary needs";content="Create a {{Duration}}-day meal plan for {{DietaryPreference}}. Calories: {{Calories}} kcal/day. Meals per day: {{Meals}}. Breakfast: {{Breakfast}}. Lunch: {{Lunch}}. Dinner: {{Dinner}}. Snacks: {{Snack1}}, {{Snack2}}. Nutritional targets: protein {{Protein}}g, carbs {{Carbs}}g, fat {{Fat}}g. Allergies: {{Allergies}}. Prep time: {{PrepTime}}. Grocery list: {{GroceryList}}.";diff="Beginner";use="Health-conscious individuals and nutritionists";tags=@("meal-plan","nutrition","diet");vars=@("Duration","DietaryPreference","Calories","Meals","Breakfast","Lunch","Dinner","Snack1","Snack2","Protein","Carbs","Fat","Allergies","PrepTime","GroceryList")},
  @{title="Meditation Script Generator";slug="meditation-script-generator";desc="Guided meditation scripts";content="Write a {{Duration}}-minute guided meditation. Type: {{Type}}. Theme: {{Theme}}. Setting: {{Setting}}. Breathing pattern: {{BreathingPattern}}. Body scan: {{BodyScan}}. Visualization: {{Visualization}}. Affirmations: {{Affirmation1}}, {{Affirmation2}}. Music suggestion: {{Music}}. Closing: {{Closing}}. Difficulty: {{Difficulty}}.";diff="Intermediate";use="Meditation teachers and wellness coaches";tags=@("meditation","mindfulness","wellness");vars=@("Duration","Type","Theme","Setting","BreathingPattern","BodyScan","Visualization","Affirmation1","Affirmation2","Music","Closing","Difficulty")},
  @{title="Sleep Improvement Plan";slug="sleep-improvement-plan";desc="Evidence-based sleep optimization";content="Create a sleep improvement plan for {{AgeGroup}}. Current sleep: {{CurrentHours}} hours. Goal: {{GoalHours}} hours. Bedtime routine: {{Routine1}}, {{Routine2}}, {{Routine3}}. Environment: {{Environment}}. Diet adjustments: {{DietAdjustments}}. Screen time: {{ScreenTime}} before bed. Exercise: {{ExerciseTiming}}. Supplements: {{Supplements}}. Tracking: {{TrackingMethod}}. Duration: {{Duration}} weeks.";diff="Beginner";use="Anyone seeking better sleep";tags=@("sleep","health","wellness");vars=@("AgeGroup","CurrentHours","GoalHours","Routine1","Routine2","Routine3","Environment","DietAdjustments","ScreenTime","ExerciseTiming","Supplements","TrackingMethod","Duration")},
  @{title="Stress Management Plan";slug="stress-management-plan";desc="Personalized stress reduction strategies";content="Create a stress management plan for {{PersonName}}. Stress sources: {{Source1}}, {{Source2}}, {{Source3}}. Current coping: {{CurrentCoping}}. Techniques: {{Technique1}}, {{Technique2}}, {{Technique3}}. Daily practice: {{DailyPractice}} ({{Minutes}}min). Journal prompts: {{Prompt1}}, {{Prompt2}}. Support system: {{Support}}. Measurement: {{Measurement}}. Review: {{ReviewFrequency}}.";diff="Intermediate";use="Wellness coaches and individuals";tags=@("stress","mental-health","wellness");vars=@("PersonName","Source1","Source2","Source3","CurrentCoping","Technique1","Technique2","Technique3","DailyPractice","Minutes","Prompt1","Prompt2","Support","Measurement","ReviewFrequency")},
  @{title="Habit Tracker Builder";slug="habit-tracker-builder";desc="Design effective habit tracking systems";content="Design a habit tracker for {{Goal}}. Habits to build: {{Habit1}}, {{Habit2}}, {{Habit3}}. Habits to quit: {{Quit1}}, {{Quit2}}. Frequency: {{Frequency}}. Tracking method: {{Method}}. Rewards: {{Reward1}}, {{Reward2}}. Accountability: {{Accountability}}. Duration: {{Duration}} days. Start date: {{StartDate}}. Notes: {{Notes}}.";diff="Beginner";use="Self-improvement seekers";tags=@("habits","tracking","productivity");vars=@("Goal","Habit1","Habit2","Habit3","Quit1","Quit2","Frequency","Method","Reward1","Reward2","Accountability","Duration","StartDate","Notes")},
  @{title="Yoga Sequence Generator";slug="yoga-sequence-generator";desc="Balanced yoga flow sequences";content="Create a {{Duration}}-minute yoga sequence. Style: {{Style}}. Level: {{Level}}. Focus: {{Focus}}. Warmup: {{Warmup}}. Main poses: {{Pose1}}, {{Pose2}}, {{Pose3}}, {{Pose4}}, {{Pose5}}. Breath cues: {{BreathCues}}. Peak pose: {{PeakPose}}. Cool down: {{CoolDown}}. Prop needs: {{Props}}. Intention: {{Intention}}.";diff="Intermediate";use="Yoga teachers and practitioners";tags=@("yoga","fitness","mindfulness");vars=@("Duration","Style","Level","Focus","Warmup","Pose1","Pose2","Pose3","Pose4","Pose5","BreathCues","PeakPose","CoolDown","Props","Intention")},
  @{title="Wellness Challenge Creator";slug="wellness-challenge-creator";desc="Engaging wellness challenges";content="Design a {{Duration}}-day wellness challenge called '{{ChallengeName}}'. Theme: {{Theme}}. Daily tasks: {{Task1}}, {{Task2}}, {{Task3}}. Check-in: {{CheckInMethod}}. Community: {{Community}}. Prizes: {{Prize1}}, {{Prize2}}. Difficulty: {{Difficulty}}. Required resources: {{Resources}}. Tracking: {{Tracking}}. Sample day: {{SampleDay}}.";diff="Beginner";use="Wellness program coordinators";tags=@("challenge","wellness","community");vars=@("Duration","ChallengeName","Theme","Task1","Task2","Task3","CheckInMethod","Community","Prize1","Prize2","Difficulty","Resources","Tracking","SampleDay")},
  @{title="Journaling Prompt Generator";slug="journaling-prompt-generator";desc="Meaningful journaling prompts";content="Generate {{Count}} journaling prompts for {{Theme}}. Format: {{Format}}. Focus areas: {{Area1}}, {{Area2}}, {{Area3}}. Style: {{Style}}. Time per prompt: {{TimePerPrompt}} minutes. Examples: morning {{MorningPrompt}}, evening {{EveningPrompt}}, gratitude {{GratitudePrompt}}. Emotion: {{Emotion}}. Outcome: {{Outcome}}.";diff="Beginner";use="Journaling enthusiasts and therapists";tags=@("journaling","reflection","mental-health");vars=@("Count","Theme","Format","Area1","Area2","Area3","Style","TimePerPrompt","MorningPrompt","EveningPrompt","GratitudePrompt","Emotion","Outcome")},
  @{title="Posture Correction Guide";slug="posture-correction-guide";desc="Ergonomic posture improvement plans";content="Create a posture improvement plan for {{WorkType}} workers. Assessment: {{Assessment}}. Key issues: {{Issue1}}, {{Issue2}}. Stretches: {{Stretch1}}, {{Stretch2}}, {{Stretch3}}. Strengthening: {{Exercise1}}, {{Exercise2}}. Workspace setup: {{WorkspaceSetup}}. Break schedule: {{BreakSchedule}}. Reminders: {{ReminderMethod}}. Duration: {{Duration}} weeks. Progress markers: {{Markers}}.";diff="Intermediate";use="Desk workers and ergonomics specialists";tags=@("posture","ergonomics","health");vars=@("WorkType","Assessment","Issue1","Issue2","Stretch1","Stretch2","Stretch3","Exercise1","Exercise2","WorkspaceSetup","BreakSchedule","ReminderMethod","Duration","Markers")},
  @{title="Hydration Tracker Setup";slug="hydration-tracker-setup";desc="Personalized hydration goals";content="Create a hydration plan for {{PersonName}}. Weight: {{Weight}} kg. Activity level: {{ActivityLevel}}. Daily goal: {{Goal}} liters. Tracking method: {{Method}}. Reminders: every {{ReminderInterval}} minutes. Fluids: water {{WaterPct}}%, tea {{TeaPct}}%, other {{OtherPct}}%. Electrolytes: {{Electrolytes}}. Hydration foods: {{Food1}}, {{Food2}}. Signs of dehydration: {{Sign1}}, {{Sign2}}. Duration: {{Duration}}.";diff="Beginner";use="Health-conscious individuals";tags=@("hydration","health","tracking");vars=@("PersonName","Weight","ActivityLevel","Goal","Method","ReminderInterval","WaterPct","TeaPct","OtherPct","Electrolytes","Food1","Food2","Sign1","Sign2","Duration")},
  @{title="Health Goal Planner";slug="health-goal-planner";desc="SMART health goal setting";content="Create a SMART health plan for {{Goal}}. Specific: {{Specific}}. Measurable: {{Measurable}}. Achievable: {{Achievable}}. Relevant: {{Relevant}}. Time-bound: {{Timeframe}}. Action steps: {{Step1}}, {{Step2}}, {{Step3}}, {{Step4}}. Obstacles: {{Obstacle1}}, {{Obstacle2}}. Support: {{Support}}. Tracking: {{Tracking}}. Review: {{ReviewDate}}.";diff="Beginner";use="Anyone setting health goals";tags=@("goals","health","planning");vars=@("Goal","Specific","Measurable","Achievable","Relevant","Timeframe","Step1","Step2","Step3","Step4","Obstacle1","Obstacle2","Support","Tracking","ReviewDate")}
)
foreach ($p in $hw) { $p.category_id = $cats.healthwellness; $prompts += $p }

# ─── MARKETING (13) ───
$mk = @(
  @{title="Ad Copy Generator";slug="ad-copy-generator";desc="High-performing ad copy for any platform";content="Write {{Count}} ad copies for {{Platform}}. Product: {{ProductName}}. Audience: {{Audience}}. Key benefit: {{Benefit}}. Tone: {{Tone}}. CTA: {{CTA}}. Headline: {{Headline}}. Budget: `${{Budget}}. Goal: {{Goal}}. Include A/B test variants. Ad format: {{Format}}. Character limit: {{CharLimit}}.";diff="Intermediate";use="Digital marketers and advertisers";tags=@("advertising","copy","ppc");vars=@("Count","Platform","ProductName","Audience","Benefit","Tone","CTA","Headline","Budget","Goal","Format","CharLimit")},
  @{title="SEO Meta Tag Generator";slug="seo-meta-tag-generator";desc="Optimized meta tags for search ranking";content="Generate SEO meta tags for {{PageTitle}}. Primary keyword: {{PrimaryKW}}. Secondary keywords: {{KW2}}, {{KW3}}. Meta title: {{MetaTitle}} ({{TitleLen}} chars). Meta description: {{MetaDescription}} ({{DescLen}} chars). Focus: {{Focus}}. Page type: {{PageType}}. Include Open Graph tags: {{OGTitle}}, {{OGDescription}}. Twitter card: {{TwitterCard}}. Schema type: {{SchemaType}}.";diff="Beginner";use="SEO specialists and content managers";tags=@("seo","meta","tags");vars=@("PageTitle","PrimaryKW","KW2","KW3","MetaTitle","TitleLen","MetaDescription","DescLen","Focus","PageType","OGTitle","OGDescription","TwitterCard","SchemaType")},
  @{title="Content Calendar Creator";slug="content-calendar-creator";desc="Strategic content calendars";content="Create a {{Duration}}-month content calendar for {{Brand}}. Platforms: {{Platform1}}, {{Platform2}}, {{Platform3}}. Content pillars: {{Pillar1}}, {{Pillar2}}, {{Pillar3}}. Post frequency: {{Frequency}} posts/week. Campaigns: {{Campaign1}}, {{Campaign2}}. Key dates: {{Date1}}, {{Date2}}. Content mix: {{Mix}} (educational {{EduPct}}%, promotional {{PromoPct}}%, engagement {{EngPct}}%). Goals: {{Goal1}}, {{Goal2}}.";diff="Advanced";use="Content strategists and marketing managers";tags=@("content-calendar","strategy","planning");vars=@("Duration","Brand","Platform1","Platform2","Platform3","Pillar1","Pillar2","Pillar3","Frequency","Campaign1","Campaign2","Date1","Date2","Mix","EduPct","PromoPct","EngPct","Goal1","Goal2")},
  @{title="Influencer Brief Template";slug="influencer-brief-template";desc="Professional influencer collaboration briefs";content="Create a campaign brief for influencer {{InfluencerName}}. Campaign: {{CampaignName}}. Product: {{Product}}. Key message: {{Message}}. Deliverables: {{Deliverable1}}, {{Deliverable2}}, {{Deliverable3}}. Timeline: {{Timeline}}. Compensation: {{Compensation}}. Usage rights: {{UsageRights}}. Brand guidelines: {{Guidelines}}. Approval process: {{Approval}}. Tags/hashtags: {{Hashtags}}.";diff="Intermediate";use="Brand managers and influencer marketers";tags=@("influencer","brief","campaign");vars=@("InfluencerName","CampaignName","Product","Message","Deliverable1","Deliverable2","Deliverable3","Timeline","Compensation","UsageRights","Guidelines","Approval","Hashtags")},
  @{title="Landing Page A/B Test Plan";slug="landing-page-ab-test-plan";desc="Data-driven A/B test designs";content="Design an A/B test for {{PageURL}}. Goal: {{Goal}}. Hypothesis: {{Hypothesis}}. Variant A: {{VariantA}}. Variant B: {{VariantB}}. Element being tested: {{Element}}. Metrics: {{Metric1}}, {{Metric2}}. Sample size: {{SampleSize}}. Duration: {{Duration}} days. Confidence level: {{Confidence}}%. Risk: {{Risk}}. Winning variant: {{Winner}}. Next steps: {{NextSteps}}.";diff="Advanced";use="Growth marketers and product managers";tags=@("ab-test","conversion","optimization");vars=@("PageURL","Goal","Hypothesis","VariantA","VariantB","Element","Metric1","Metric2","SampleSize","Duration","Confidence","Risk","Winner","NextSteps")},
  @{title="Brand Voice Guide";slug="brand-voice-guide";desc="Define and document brand voice";content="Create a brand voice guide for {{BrandName}}. Personality: {{Personality1}}, {{Personality2}}, {{Personality3}}. Tone variations: {{Tone1}}, {{Tone2}}, {{Tone3}}. Do say: {{Do1}}, {{Do2}}. Don't say: {{Dont1}}, {{Dont2}}. Vocabulary: {{Vocab1}}, {{Vocab2}}. Grammar style: {{GrammarStyle}}. Examples: {{Example1}}, {{Example2}}. Audience: {{Audience}}. Channels: {{Channels}}.";diff="Intermediate";use="Brand strategists and copywriters";tags=@("brand-voice","branding","guidelines");vars=@("BrandName","Personality1","Personality2","Personality3","Tone1","Tone2","Tone3","Do1","Do2","Dont1","Dont2","Vocab1","Vocab2","GrammarStyle","Example1","Example2","Audience","Channels")},
  @{title="Email Sequence Designer";slug="email-sequence-designer";desc="Automated email drip campaigns";content="Design a {{EmailCount}}-email sequence for {{Goal}}. Target: {{Target}}. Trigger: {{Trigger}}. Email 1 ({{Day1}}): {{Subject1}} — {{Content1}}. Email 2 ({{Day2}}): {{Subject2}} — {{Content2}}. Email 3 ({{Day3}}): {{Subject3}} — {{Content3}}. Personalization: {{Personalization}}. Goals: open rate {{OpenRate}}%, CTR {{CTR}}%. Unsubscribe: {{Unsubscribe}}.";diff="Advanced";use="Email marketers and automation specialists";tags=@("email","sequence","automation");vars=@("EmailCount","Goal","Target","Trigger","Day1","Subject1","Content1","Day2","Subject2","Content2","Day3","Subject3","Content3","Personalization","OpenRate","CTR","Unsubscribe")},
  @{title="Social Media Strategy";slug="social-media-strategy";desc="Comprehensive social media plans";content="Create a {{Duration}}-month social media strategy for {{Brand}}. Platforms: {{Platform1}}, {{Platform2}}. Goals: {{Goal1}}, {{Goal2}}. Target audience: {{Audience}}. Content themes: {{Theme1}}, {{Theme2}}, {{Theme3}}. Posting schedule: {{Schedule}}. Ad budget: `${{Budget}}. KPIs: {{KPI1}}, {{KPI2}}. Competitor analysis: {{Competitor1}}, {{Competitor2}}. Tools: {{Tool1}}, {{Tool2}}. Reporting: {{ReportFrequency}}.";diff="Advanced";use="Social media managers and marketers";tags=@("social-media","strategy","marketing");vars=@("Duration","Brand","Platform1","Platform2","Goal1","Goal2","Audience","Theme1","Theme2","Theme3","Schedule","Budget","KPI1","KPI2","Competitor1","Competitor2","Tool1","Tool2","ReportFrequency")},
  @{title="Customer Persona Builder";slug="customer-persona-builder";desc="Detailed buyer personas";content="Create a customer persona for {{ProductName}}. Name: {{PersonaName}}. Age: {{Age}}. Occupation: {{Occupation}}. Income: `${{Income}}. Goals: {{Goal1}}, {{Goal2}}. Pain points: {{Pain1}}, {{Pain2}}, {{Pain3}}. Motivations: {{Motivation1}}, {{Motivation2}}. Channels: {{Channel1}}, {{Channel2}}. Objections: {{Objection1}}, {{Objection2}}. Brand affinity: {{Brands}}. Quote: '{{Quote}}'.";diff="Intermediate";use="Product marketers and UX researchers";tags=@("persona","customer","marketing");vars=@("ProductName","PersonaName","Age","Occupation","Income","Goal1","Goal2","Pain1","Pain2","Pain3","Motivation1","Motivation2","Channel1","Channel2","Objection1","Objection2","Brands","Quote")},
  @{title="Marketing Funnel Designer";slug="marketing-funnel-designer";desc="Full-funnel marketing strategies";content="Design a marketing funnel for {{ProductName}}. Funnel type: {{FunnelType}}. Awareness: {{AwarenessChannel}} — {{AwarenessContent}}. Interest: {{InterestChannel}} — {{InterestContent}}. Decision: {{DecisionChannel}} — {{DecisionContent}}. Action: {{ActionChannel}} — {{ActionContent}}. Retention: {{RetentionStrategy}}. Metrics: top {{TopMetric}}, middle {{MidMetric}}, bottom {{BottomMetric}}.";diff="Advanced";use="Marketing strategists and growth teams";tags=@("funnel","marketing","strategy");vars=@("ProductName","FunnelType","AwarenessChannel","AwarenessContent","InterestChannel","InterestContent","DecisionChannel","DecisionContent","ActionChannel","ActionContent","RetentionStrategy","TopMetric","MidMetric","BottomMetric")},
  @{title="Hashtag Research Tool";slug="hashtag-research-tool";desc="Strategic hashtag sets for reach";content="Research hashtags for {{Topic}} on {{Platform}}. Primary hashtags: {{Hash1}}, {{Hash2}}, {{Hash3}} (volume: {{Vol1}}, {{Vol2}}, {{Vol3}}). Secondary: {{Hash4}}, {{Hash5}}, {{Hash6}}. Niche: {{NicheHash1}}, {{NicheHash2}}. Branded: {{BrandedHash}}. Recommended mix: {{MixCount}} per post. Strategy: {{Strategy}}. Trending: {{Trending}}.";diff="Beginner";use="Social media managers and content creators";tags=@("hashtags","social-media","reach");vars=@("Topic","Platform","Hash1","Hash2","Hash3","Vol1","Vol2","Vol3","Hash4","Hash5","Hash6","NicheHash1","NicheHash2","BrandedHash","MixCount","Strategy","Trending")},
  @{title="Product Launch Plan";slug="product-launch-plan";desc="Go-to-market launch strategies";content="Create a {{Duration}}-week product launch plan for {{ProductName}}. Target audience: {{Audience}}. Launch date: {{LaunchDate}}. Pre-launch: {{PreLaunchActivity1}}, {{PreLaunchActivity2}}. Launch day: {{LaunchDayActivity}}. Post-launch: {{PostLaunchActivity1}}, {{PostLaunchActivity2}}. Channels: {{Channel1}}, {{Channel2}}. Budget: `${{Budget}}. Success metrics: {{Metric1}}, {{Metric2}}. Team: {{Team}}.";diff="Advanced";use="Product managers and marketers";tags=@("launch","product","go-to-market");vars=@("Duration","ProductName","Audience","LaunchDate","PreLaunchActivity1","PreLaunchActivity2","LaunchDayActivity","PostLaunchActivity1","PostLaunchActivity2","Channel1","Channel2","Budget","Metric1","Metric2","Team")},
  @{title="Referral Program Designer";slug="referral-program-designer";desc="Viral referral program structures";content="Design a referral program for {{CompanyName}}. Incentive for referrer: {{ReferrerReward}}. Incentive for friend: {{FriendReward}}. Program name: {{ProgramName}}. Trigger: {{Trigger}}. Sharing methods: {{Method1}}, {{Method2}}. Conversion goal: {{Goal}}. Budget: `${{Budget}}. Tracking: {{Tracking}}. Duration: {{Duration}}. Promotion plan: {{PromotionPlan}}.";diff="Intermediate";use="Growth marketers and founders";tags=@("referral","growth","viral");vars=@("CompanyName","ReferrerReward","FriendReward","ProgramName","Trigger","Method1","Method2","Goal","Budget","Tracking","Duration","PromotionPlan")}
)
foreach ($p in $mk) { $p.category_id = $cats.marketing; $prompts += $p }

# ─── PRODUCTIVITY (13) ───
$pr = @(
  @{title="Daily Routine Optimizer";slug="daily-routine-optimizer";desc="Optimize your daily schedule";content="Design an optimized daily routine for {{PersonType}}. Wake time: {{WakeTime}}. Sleep time: {{SleepTime}}. Work hours: {{WorkHours}}. Deep work blocks: {{DeepWorkBlocks}} ({{DeepWorkDuration}}min each). Breaks: {{BreakFrequency}} ({{BreakDuration}}min). Exercise: {{ExerciseTime}}. Meals: {{MealTimes}}. Learning: {{LearningTime}}. Wind-down: {{WindDown}}. Energy management: {{EnergyStrategy}}.";diff="Beginner";use="Professionals and self-optimizers";tags=@("routine","productivity","time-management");vars=@("PersonType","WakeTime","SleepTime","WorkHours","DeepWorkBlocks","DeepWorkDuration","BreakFrequency","BreakDuration","ExerciseTime","MealTimes","LearningTime","WindDown","EnergyStrategy")},
  @{title="Task Priority Matrix";slug="task-priority-matrix";desc="Eisenhower matrix for task management";content="Create a priority matrix for {{ProjectName}}. Tasks: list {{TaskCount}} tasks. Quadrant 1 (urgent+important): {{Q1Task1}}, {{Q1Task2}}. Quadrant 2 (not urgent+important): {{Q2Task1}}, {{Q2Task2}}. Quadrant 3 (urgent+not important): {{Q3Task1}}, {{Q3Task2}}. Quadrant 4: {{Q4Task1}}. Focus: {{Focus}}. Review: {{ReviewSchedule}}. Tool: {{Tool}}.";diff="Beginner";use="Project managers and individuals";tags=@("priority","matrix","productivity");vars=@("ProjectName","TaskCount","Q1Task1","Q1Task2","Q2Task1","Q2Task2","Q3Task1","Q3Task2","Q4Task1","Focus","ReviewSchedule","Tool")},
  @{title="Project Timeline Generator";slug="project-timeline-generator";desc="Gantt-style project timelines";content="Create a project timeline for {{ProjectName}}. Duration: {{Duration}} weeks. Phases: {{Phase1}} ({{W1}} weeks), {{Phase2}} ({{W2}} weeks), {{Phase3}} ({{W3}} weeks). Milestones: {{Milestone1}} (week {{MW1}}), {{Milestone2}} (week {{MW2}}), {{Milestone3}} (week {{MW3}}). Team: {{TeamSize}} members. Dependencies: {{Dependency1}}, {{Dependency2}}. Risks: {{Risk1}}, {{Risk2}}. Buffer: {{Buffer}} days.";diff="Intermediate";use="Project managers and team leads";tags=@("timeline","project","planning");vars=@("ProjectName","Duration","Phase1","W1","Phase2","W2","Phase3","W3","Milestone1","MW1","Milestone2","MW2","Milestone3","MW3","TeamSize","Dependency1","Dependency2","Risk1","Risk2","Buffer")},
  @{title="Meeting Notes Template";slug="meeting-notes-template";desc="Structured meeting documentation";content="Create meeting notes for {{MeetingTitle}}. Date: {{Date}}. Attendees: {{Attendees}}. Absent: {{Absent}}. Agenda: {{Agenda}}. Discussion: {{Discussion}}. Decisions: {{Decision1}}, {{Decision2}}. Action items: {{Action1}} (owner: {{Owner1}}, due: {{Due1}}), {{Action2}} (owner: {{Owner2}}, due: {{Due2}}). Next meeting: {{NextMeeting}}. Attachments: {{Attachments}}.";diff="Beginner";use="Anyone who attends meetings";tags=@("meeting","notes","documentation");vars=@("MeetingTitle","Date","Attendees","Absent","Agenda","Discussion","Decision1","Decision2","Action1","Owner1","Due1","Action2","Owner2","Due2","NextMeeting","Attachments")},
  @{title="Goal Setting Framework";slug="goal-setting-framework";desc="OKR and SMART goal setting";content="Set {{GoalType}} goals for {{Context}}. Objective: {{Objective}}. Key results: {{KR1}} ({{KR1Metric}}), {{KR2}} ({{KR2Metric}}), {{KR3}} ({{KR3Metric}}). Initiatives: {{Initiative1}}, {{Initiative2}}. Timeline: {{Timeline}}. Owner: {{Owner}}. Progress tracking: {{Tracking}}. Stretch goal: {{Stretch}}. Monthly review: {{Review}}.";diff="Intermediate";use="Team leads and individuals";tags=@("goals","okr","planning");vars=@("GoalType","Context","Objective","KR1","KR1Metric","KR2","KR2Metric","KR3","KR3Metric","Initiative1","Initiative2","Timeline","Owner","Tracking","Stretch","Review")},
  @{title="Focus Timer Setup";slug="focus-timer-setup";desc="Pomodoro and focus session designs";content="Design a focus session plan for {{WorkType}}. Technique: {{Technique}}. Work duration: {{WorkDuration}} minutes. Break: {{BreakDuration}} minutes. Long break after: {{LongBreakAfter}} cycles. Long break: {{LongBreak}} minutes. Sessions per day: {{DailySessions}}. Goals per session: {{SessionGoal1}}, {{SessionGoal2}}. Distraction management: {{DistractionStrategy}}. Tools: {{Tool1}}, {{Tool2}}. Tracking: {{Tracking}}.";diff="Beginner";use="Students and knowledge workers";tags=@("focus","pomodoro","time-management");vars=@("WorkType","Technique","WorkDuration","BreakDuration","LongBreakAfter","LongBreak","DailySessions","SessionGoal1","SessionGoal2","DistractionStrategy","Tool1","Tool2","Tracking")},
  @{title="Email Management System";slug="email-management-system";desc="Inbox zero productivity system";content="Design an email management system for {{PersonType}}. Current inbox: {{CurrentCount}} emails. Processing frequency: {{Frequency}}. Folder structure: {{Folder1}}, {{Folder2}}, {{Folder3}}. Labels: {{Label1}}, {{Label2}}. Templates: {{Template1}}, {{Template2}}. Auto-responders: {{AutoResponder}}. Unsubscribe strategy: {{Unsubscribe}}. Goal: {{Goal}} minutes/day. Tool: {{Tool}}. Review: {{Review}}.";diff="Beginner";use="Professionals overwhelmed by email";tags=@("email","inbox-zero","productivity");vars=@("PersonType","CurrentCount","Frequency","Folder1","Folder2","Folder3","Label1","Label2","Template1","Template2","AutoResponder","Unsubscribe","Goal","Tool","Review")},
  @{title="Weekly Review Template";slug="weekly-review-template";desc="Structured weekly reflection system";content="Conduct a weekly review for {{PersonName}}. Week: {{WeekNumber}}. Wins: {{Win1}}, {{Win2}}, {{Win3}}. Challenges: {{Challenge1}}, {{Challenge2}}. Lessons: {{Lesson1}}, {{Lesson2}}. Next week priorities: {{Priority1}}, {{Priority2}}, {{Priority3}}. Schedule: {{Schedule}}. Energy levels: {{Energy}}. Focus for next week: {{Focus}}. Gratitude: {{Gratitude}}.";diff="Beginner";use="Self-improvement and reflection";tags=@("review","reflection","productivity");vars=@("PersonName","WeekNumber","Win1","Win2","Win3","Challenge1","Challenge2","Lesson1","Lesson2","Priority1","Priority2","Priority3","Schedule","Energy","Focus","Gratitude")},
  @{title="Time Audit Tool";slug="time-audit-tool";desc="Analyze and optimize time usage";content="Perform a time audit for {{PersonName}}. Tracked period: {{Duration}} days. Categories: {{Category1}} ({{C1Pct}}%), {{Category2}} ({{C2Pct}}%), {{Category3}} ({{C3Pct}}%), {{Category4}} ({{C4Pct}}%). Time wasters: {{Waster1}}, {{Waster2}}. Productive hours: {{ProductiveHours}}/day. Recommendations: {{Rec1}}, {{Rec2}}, {{Rec3}}. Target reallocation: {{Target}}. Follow-up: {{FollowUp}}.";diff="Intermediate";use="Productivity coaches and individuals";tags=@("time-audit","productivity","analysis");vars=@("PersonName","Duration","Category1","C1Pct","Category2","C2Pct","Category3","C3Pct","Category4","C4Pct","Waster1","Waster2","ProductiveHours","Rec1","Rec2","Rec3","Target","FollowUp")},
  @{title="Decision Matrix Generator";slug="decision-matrix-generator";desc="Data-driven decision making framework";content="Create a decision matrix for {{Decision}}. Options: {{Option1}}, {{Option2}}, {{Option3}}. Criteria: {{Criterion1}} (weight {{W1}}), {{Criterion2}} (weight {{W2}}), {{Criterion3}} (weight {{W3}}), {{Criterion4}} (weight {{W4}}). Score each option (1-5) per criterion. Winner: {{Winner}}. Rationale: {{Rationale}}. Risk: {{Risk}}. Next steps: {{NextSteps}}.";diff="Intermediate";use="Decision makers and analysts";tags=@("decision","matrix","analysis");vars=@("Decision","Option1","Option2","Option3","Criterion1","W1","Criterion2","W2","Criterion3","W3","Criterion4","W4","Winner","Rationale","Risk","NextSteps")},
  @{title="Workspace Setup Guide";slug="workspace-setup-guide";desc="Ergonomic and productive workspace design";content="Design a productive workspace for {{WorkType}}. Desk: {{DeskType}}. Chair: {{ChairType}}. Monitor: {{MonitorSetup}}. Lighting: {{Lighting}}. Noise management: {{NoiseStrategy}}. Plants: {{Plants}}. Organization: {{OrganizationSystem}}. Tools: {{Tool1}}, {{Tool2}}. Personalization: {{Personalization}}. Budget: `${{Budget}}. Setup time: {{SetupTime}}.";diff="Beginner";use="Remote workers and office employees";tags=@("workspace","setup","productivity");vars=@("WorkType","DeskType","ChairType","MonitorSetup","Lighting","NoiseStrategy","Plants","OrganizationSystem","Tool1","Tool2","Personalization","Budget","SetupTime")},
  @{title="Batch Processing Plan";slug="batch-processing-plan";desc="Efficient task batching system";content="Design a batch processing system for {{WorkType}}. Tasks to batch: {{Task1}}, {{Task2}}, {{Task3}}, {{Task4}}. Batching schedule: {{Schedule}}. Time blocks: {{Block1}} ({{B1Duration}}min), {{Block2}} ({{B2Duration}}min). Preparation: {{Preparation}}. Tools: {{Tool}}. Transition ritual: {{Ritual}}. Metrics: tasks completed {{TasksPerDay}}, time saved {{TimeSaved}}. Review: {{Review}}.";diff="Intermediate";use="Productivity enthusiasts";tags=@("batching","productivity","workflow");vars=@("WorkType","Task1","Task2","Task3","Task4","Schedule","Block1","B1Duration","Block2","B2Duration","Preparation","Tool","Ritual","TasksPerDay","TimeSaved","Review")},
  @{title="Energy Management Plan";slug="energy-management-plan";desc="Manage energy, not just time";content="Create an energy management plan for {{PersonName}}. Chronotype: {{Chronotype}}. Peak energy: {{PeakTime}}. Low energy: {{LowTime}}. High-focus tasks: schedule during {{HighFocusTime}}. Low-focus tasks: schedule during {{LowFocusTime}}. Energy boosters: {{Booster1}}, {{Booster2}}. Energy drainers: {{Drainer1}}, {{Drainer2}}. Sleep hygiene: {{SleepHygiene}}. Nutrition: {{Nutrition}}. Exercise: {{Exercise}}. Breaks: {{BreakStrategy}}.";diff="Intermediate";use="High-performers and executives";tags=@("energy","productivity","wellness");vars=@("PersonName","Chronotype","PeakTime","LowTime","HighFocusTime","LowFocusTime","Booster1","Booster2","Drainer1","Drainer2","SleepHygiene","Nutrition","Exercise","BreakStrategy")}
)
foreach ($p in $pr) { $p.category_id = $cats.productivity; $prompts += $p }

# ─── PROGRAMMING (14) ───
$pg = @(
  @{title="Code Review Assistant";slug="code-review-assistant";desc="Thorough code review automation";content="Review code for {{Language}} project {{ProjectName}}. Code purpose: {{Purpose}}. Focus areas: {{Focus1}}, {{Focus2}}, {{Focus3}}. Issues found: {{Issue1}} (severity: {{Sev1}}), {{Issue2}} (severity: {{Sev2}}), {{Issue3}} (severity: {{Sev3}}). Recommendations: {{Rec1}}, {{Rec2}}. Performance: {{Performance}}. Security: {{Security}}. Style: {{Style}}. Overall: {{OverallRating}}/10.";diff="Advanced";use="Developers and engineering teams";tags=@("code-review","programming","quality");vars=@("Language","ProjectName","Purpose","Focus1","Focus2","Focus3","Issue1","Sev1","Issue2","Sev2","Issue3","Sev3","Rec1","Rec2","Performance","Security","Style","OverallRating")},
  @{title="API Endpoint Designer";slug="api-endpoint-designer";desc="RESTful API design";content="Design an API for {{ProjectName}}. Base URL: {{BaseURL}}. Authentication: {{Auth}}. Endpoints: 1. {{Method1}} {{Path1}} — {{Desc1}}, 2. {{Method2}} {{Path2}} — {{Desc2}}, 3. {{Method3}} {{Path3}} — {{Desc3}}. Request body: {{RequestBody}}. Response format: {{ResponseFormat}}. Error codes: {{Error1}}, {{Error2}}. Rate limit: {{RateLimit}}. Version: {{Version}}.";diff="Intermediate";use="Backend developers and API designers";tags=@("api","rest","backend");vars=@("ProjectName","BaseURL","Auth","Method1","Path1","Desc1","Method2","Path2","Desc2","Method3","Path3","Desc3","RequestBody","ResponseFormat","Error1","Error2","RateLimit","Version")},
  @{title="Bug Report Generator";slug="bug-report-generator";desc="Structured bug reports for developers";content="Create a bug report for {{ProjectName}}. Bug title: {{BugTitle}}. Environment: {{Environment}}. Severity: {{Severity}}. Steps to reproduce: 1. {{Step1}}, 2. {{Step2}}, 3. {{Step3}}. Expected: {{Expected}}. Actual: {{Actual}}. Logs: {{Logs}}. Screenshot: {{Screenshot}}. Frequency: {{Frequency}}. Reported by: {{Reporter}}. Priority: {{Priority}}.";diff="Beginner";use="QA testers and developers";tags=@("bug","report","testing");vars=@("ProjectName","BugTitle","Environment","Severity","Step1","Step2","Step3","Expected","Actual","Logs","Screenshot","Frequency","Reporter","Priority")},
  @{title="Database Schema Designer";slug="database-schema-designer";desc="Design normalized database schemas";content="Design a database schema for {{AppType}}. Tables: {{Table1}} (columns: {{Cols1}}), {{Table2}} (columns: {{Cols2}}), {{Table3}} (columns: {{Cols3}}). Relationships: {{Rel1}}, {{Rel2}}. Indexes: {{Index1}}, {{Index2}}. Database: {{DBType}}. Constraints: {{Constraint1}}, {{Constraint2}}. Estimated rows: {{RowEstimate}}. Migration strategy: {{MigrationStrategy}}.";diff="Advanced";use="Backend developers and DBAs";tags=@("database","schema","sql");vars=@("AppType","Table1","Cols1","Table2","Cols2","Table3","Cols3","Rel1","Rel2","Index1","Index2","DBType","Constraint1","Constraint2","RowEstimate","MigrationStrategy")},
  @{title="Unit Test Generator";slug="unit-test-generator";desc="Comprehensive unit test suites";content="Write unit tests for {{FunctionName}} in {{Language}}. Framework: {{Framework}}. Test cases: {{Case1}} (input: {{In1}}, expected: {{Exp1}}), {{Case2}} (input: {{In2}}, expected: {{Exp2}}), {{Case3}} (input: {{In3}}, expected: {{Exp3}}). Edge cases: {{Edge1}}, {{Edge2}}. Mocks: {{Mock1}}, {{Mock2}}. Coverage target: {{Coverage}}%. Run command: {{RunCommand}}.";diff="Intermediate";use="Software developers and QA engineers";tags=@("testing","unit-test","quality");vars=@("FunctionName","Language","Framework","Case1","In1","Exp1","Case2","In2","Exp2","Case3","In3","Exp3","Edge1","Edge2","Mock1","Mock2","Coverage","RunCommand")},
  @{title="Git Workflow Designer";slug="git-workflow-designer";desc="Custom Git branching strategies";content="Design a Git workflow for {{TeamSize}} developers working on {{ProjectName}}. Branching model: {{Model}}. Main branches: {{MainBranch}}, {{DevBranch}}. Feature branches: {{FeatureBranch}}. Release process: {{ReleaseProcess}}. Hotfix: {{HotfixProcess}}. Code review: {{ReviewProcess}}. CI/CD: {{CICD}}. Merge strategy: {{MergeStrategy}}. Tags: {{Tags}}. Commit convention: {{CommitConvention}}.";diff="Intermediate";use="Engineering teams and tech leads";tags=@("git","workflow","version-control");vars=@("TeamSize","ProjectName","Model","MainBranch","DevBranch","FeatureBranch","ReleaseProcess","HotfixProcess","ReviewProcess","CICD","MergeStrategy","Tags","CommitConvention")},
  @{title="Docker Compose Generator";slug="docker-compose-generator";desc="Containerized app configurations";content="Create a Docker setup for {{AppName}}. Services: {{Service1}} (image: {{Image1}}, port: {{Port1}}), {{Service2}} (image: {{Image2}}, port: {{Port2}}), {{Service3}} (image: {{Image3}}, port: {{Port3}}). Volumes: {{Volume1}}, {{Volume2}}. Networks: {{Network}}. Environment: {{EnvVars}}. Dependencies: {{Dep1}}, {{Dep2}}. Health checks: {{HealthCheck}}. Resources: {{Resources}}. Deploy: {{DeployStrategy}}.";diff="Advanced";use="DevOps engineers and developers";tags=@("docker","containers","devops");vars=@("AppName","Service1","Image1","Port1","Service2","Image2","Port2","Service3","Image3","Port3","Volume1","Volume2","Network","EnvVars","Dep1","Dep2","HealthCheck","Resources","DeployStrategy")},
  @{title="Code Documentation Generator";slug="code-documentation-generator";desc="Auto-generate code documentation";content="Generate documentation for {{ComponentName}} in {{Language}}. Purpose: {{Purpose}}. Parameters: {{Param1}} (type: {{Type1}}, desc: {{Desc1}}), {{Param2}} (type: {{Type2}}, desc: {{Desc2}}). Return: {{ReturnType}} — {{ReturnDesc}}. Exceptions: {{Exception1}}, {{Exception2}}. Example: {{Example}}. Dependencies: {{Dependency1}}, {{Dependency2}}. Notes: {{Notes}}. See also: {{SeeAlso}}.";diff="Beginner";use="Software developers";tags=@("documentation","code","comments");vars=@("ComponentName","Language","Purpose","Param1","Type1","Desc1","Param2","Type2","Desc2","ReturnType","ReturnDesc","Exception1","Exception2","Example","Dependency1","Dependency2","Notes","SeeAlso")},
  @{title="Architecture Decision Record";slug="architecture-decision-record";desc="ADR for technical decisions";content="Write an ADR for {{ProjectName}}. Title: {{ADRTitel}}. Status: {{Status}}. Context: {{Context}}. Decision: {{Decision}}. Consequences: positive: {{Positive}}, negative: {{Negative}}, neutral: {{Neutral}}. Alternatives considered: {{Alt1}}, {{Alt2}}. Rationale: {{Rationale}}. Date: {{Date}}. Author: {{Author}}.";diff="Advanced";use="Software architects and tech leads";tags=@("architecture","decision","documentation");vars=@("ProjectName","ADRTitel","Status","Context","Decision","Positive","Negative","Neutral","Alt1","Alt2","Rationale","Date","Author")},
  @{title="Debugging Strategy Guide";slug="debugging-strategy-guide";desc="Systematic debugging approaches";content="Create a debugging plan for {{IssueDescription}} in {{Environment}}. Symptoms: {{Symptom1}}, {{Symptom2}}. Hypothesis: {{Hypothesis1}}, {{Hypothesis2}}. Check: {{Check1}}, {{Check2}}, {{Check3}}. Tools: {{Tool1}}, {{Tool2}}. Logs to examine: {{Log1}}, {{Log2}}. Breakpoints: {{Breakpoint1}}, {{Breakpoint2}}. Fix approach: {{FixApproach}}. Verification: {{Verification}}. Rollback: {{RollbackPlan}}.";diff="Intermediate";use="Software developers";tags=@("debugging","troubleshooting","programming");vars=@("IssueDescription","Environment","Symptom1","Symptom2","Hypothesis1","Hypothesis2","Check1","Check2","Check3","Tool1","Tool2","Log1","Log2","Breakpoint1","Breakpoint2","FixApproach","Verification","RollbackPlan")},
  @{title="CLI Tool Creator";slug="cli-tool-creator";desc="Design command-line interfaces";content="Design a CLI tool for {{Purpose}}. Name: {{ToolName}}. Language: {{Language}}. Commands: {{Cmd1}} ({{Cmd1Desc}}), {{Cmd2}} ({{Cmd2Desc}}), {{Cmd3}} ({{Cmd3Desc}}). Flags: {{Flag1}}, {{Flag2}}, {{Flag3}}. Arguments: {{Arg1}}, {{Arg2}}. Output format: {{OutputFormat}}. Configuration: {{ConfigFile}}. Installation: {{InstallMethod}}. Dependencies: {{Dependencies}}. Testing: {{TestCommand}}. Usage example: {{UsageExample}}.";diff="Advanced";use="Developer tool builders";tags=@("cli","tool","developer-tools");vars=@("Purpose","ToolName","Language","Cmd1","Cmd1Desc","Cmd2","Cmd2Desc","Cmd3","Cmd3Desc","Flag1","Flag2","Flag3","Arg1","Arg2","OutputFormat","ConfigFile","InstallMethod","Dependencies","TestCommand","UsageExample")},
  @{title="Performance Optimization Plan";slug="performance-optimization-plan";desc="System performance improvement";content="Create a performance optimization plan for {{AppName}}. Current metrics: {{CurrentMetric1}}, {{CurrentMetric2}}. Bottlenecks: {{Bottleneck1}}, {{Bottleneck2}}. Optimization strategies: {{Strategy1}}, {{Strategy2}}, {{Strategy3}}. Expected improvement: {{Improvement}}%. Implementation order: {{Order}}. Monitoring: {{Monitoring}}. Validation: {{Validation}}. Rollback: {{Rollback}}. Timeline: {{Timeline}} weeks.";diff="Advanced";use="Backend developers and SREs";tags=@("performance","optimization","backend");vars=@("AppName","CurrentMetric1","CurrentMetric2","Bottleneck1","Bottleneck2","Strategy1","Strategy2","Strategy3","Improvement","Order","Monitoring","Validation","Rollback","Timeline")},
  @{title="Tech Stack Recommender";slug="tech-stack-recommender";desc="Technology stack selection guide";content="Recommend a tech stack for {{ProjectType}}. Frontend: {{Frontend}} (reason: {{FrontendReason}}). Backend: {{Backend}} (reason: {{BackendReason}}). Database: {{Database}} (reason: {{DBReason}}). Hosting: {{Hosting}} (reason: {{HostingReason}}). CI/CD: {{CICD}}. Monitoring: {{Monitoring}}. Budget: `${{Budget}}/month. Team size: {{TeamSize}} developers. Scalability: {{Scalability}}. Timeline: {{Timeline}}.";diff="Intermediate";use="CTOs and technical founders";tags=@("tech-stack","architecture","recommendation");vars=@("ProjectType","Frontend","FrontendReason","Backend","BackendReason","Database","DBReason","Hosting","HostingReason","CICD","Monitoring","Budget","TeamSize","Scalability","Timeline")},
  @{title="Refactoring Strategy";slug="refactoring-strategy";desc="Code refactoring plans";content="Create a refactoring plan for {{ComponentName}}. Current issues: {{Issue1}}, {{Issue2}}. Refactoring goal: {{Goal}}. Strategy: {{Strategy}}. Steps: {{Step1}}, {{Step2}}, {{Step3}}, {{Step4}}. Risks: {{Risk1}}, {{Risk2}}. Testing: {{TestStrategy}}. Estimated effort: {{Effort}} hours. Success criteria: {{Criteria}}. Timeline: {{Timeline}}. Rollback: {{Rollback}}.";diff="Advanced";use="Software developers and tech leads";tags=@("refactoring","code-quality","clean-code");vars=@("ComponentName","Issue1","Issue2","Goal","Strategy","Step1","Step2","Step3","Step4","Risk1","Risk2","TestStrategy","Effort","Criteria","Timeline","Rollback")}
)
foreach ($p in $pg) { $p.category_id = $cats.programming; $prompts += $p }

# ─── Total: 12+12+12+12+12+13+13+14 = 100 ───

Write-Host "Generated $($prompts.Length) prompts"

# Insert in batches of 10
for ($i = 0; $i -lt $prompts.Length; $i += 10) {
  $batch = $prompts[$i..([Math]::Min($i + 9, $prompts.Length - 1))]
  $values = @()
  foreach ($p in $batch) {
    $id = [guid]::NewGuid().ToString()
    $imgIdx = [array]::IndexOf($prompts, $p) + 1
    $slug = $p.slug
    $title = $p.title -replace "'", "''"
    $desc = $p.desc -replace "'", "''"
    $content = $p.content -replace "'", "''"
    $diff = $p.diff
    $use = $p.use -replace "'", "''"
    $catId = $p.category_id
    $tagsJson = ($p.tags | ForEach-Object { '"' + $_ + '"' }) -join ','
    $tagArray = "[$tagsJson]"
    $varsJson = ($p.vars | ForEach-Object { '"' + $_ + '"' }) -join ','
    $contentWithModel = $content -replace '{{ModelCompatibility}}', 'GPT-4, Claude, Gemini'
    $tagsStr = $tagArray
    $modelComp = '["GPT-4","Claude 3","Gemini Pro","Llama 3"]'
    $featured = if ($i -lt 10 -or ($imgIdx % 10) -eq 0) { 'true' } else { 'false' }
    $trending = if ($imgIdx -le 15) { 'true' } else { 'false' }
    $popularity = Get-Random -Minimum 50 -Maximum 5000
    $imgUrl = "https://picsum.photos/seed/prompt$imgIdx/800/600"

    $values += "('$id', '$title', '$slug', '$desc', '$contentWithModel', '$contentWithModel', 'published', $featured, $trending, $popularity, '$catId', '$adminId', NOW(), NOW(), NOW(), 'PromptForge Team', '$tagsStr'::jsonb, '$modelComp'::jsonb, '$use', '$diff')"
  }

  $sql = "INSERT INTO prompts (id, title, slug, description, content, prompt_template, status, featured, trending, popularity, category_id, admin_id, published_at, created_at, updated_at, author, tags, model_compatibility, use_case, difficulty) VALUES $($values -join ',') ON CONFLICT (slug) DO NOTHING;"

  $body = @{ query = $sql } | ConvertTo-Json
  try {
    $r = Invoke-RestMethod -Uri $api -Method Post -Headers @{ Authorization = "Bearer $token"; "Content-Type" = "application/json" } -Body $body -ErrorAction Stop
    Write-Host "Inserted batch $([Math]::Floor($i/10)+1): $($batch.Length) prompts"
  } catch {
    Write-Host "Batch $([Math]::Floor($i/10)+1) failed: $_"
  }
  Start-Sleep -Milliseconds 500
}

Write-Host "Done! 100 prompts inserted."
